### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by wwood** [biocore/sortmerna#100]
Hi,

I'm wondering if the maintainers could provide some guidance on what the license of sortmerna is. According to http://qiime.org/install/install.html and http://bioinfo.lifl.fr/RNA/sortmerna/ it is LPGL, and version 3 of this license is included in the repo. But, the regular GPLv3 is also included, why is that? Also, is it LGPL3 or LGPL3 or later?

ta,
ben

**Comment by ekopylova** [comment]
Hello,
The license is LGPL version 3. I've included a copy of LGPL and GPL as suggested in the [instructions](http://www.gnu.org/licenses/gpl-howto.html) for using GNU licenses, specifically: 

"Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights."

Jenya

**Comment by wwood** [comment]
Ah, ok, makes sense. I think it might pay to spell out the license in the README too, if possible. I'd rather trust you than those websites.

Seems I'd overlooked that many, but not all, source files contain the copyright notice, just fyi. I'm not so concerned about this though.

thanks.
