### ISSUE TITLE
buffer overflow when appending reverse complement

### ISSUE THREAD

**Issue by wgerlach** [biocore/sortmerna#141]
In paralleltraversal.cpp it seems the reverse complement is appended to the myread. If myread has maximal length READLEN, and myread_rc (the reverse complement) is appended, doesn't this create a buffer overflow ?

`memcpy(&myread[0],&myread_rc[0],READLEN);`

**Comment by ekopylova** [comment]
Dear Wolfgang,

Both ```myread``` and ```myread_rc``` are character arrays of size ```READLEN```. In the code you mention, I overwrite all ```READLEN``` allocated characters of ```myread``` with ```myread_rc``` (also allocated ```READLEN``` characters). The purpose is not to append ```myread_rc``` but to overwrite ```myread``` (since analysis of the forward read is complete and we no longer need it's information). Does this answer your question?

Best,
Jenya

**Comment by wgerlach** [comment]
ah. ok, thanks! I must have mixed up the variables "myread" and "_myread".
