### ISSUE TITLE
RocksDB version compatible with sortmerna

### ISSUE THREAD

**Issue by adityabandla** [biocore/sortmerna#178]
Which version of rocksdb is still compatible with the latest release of sortmerna, on Linux CentOS 6?

**Comment by biocodz** [comment]
In principle any release of RocksDB is compatible with Sortmerna for as long as Sortmerna is built with that particular release. Starting with the next Sortmerna release (3.0.3) it will be statically bundled with  RocksDB to avoid compatibility problems. We also plan to bundle a spec of all the dependencies with each release.
One thing to keep in mind is to use RocksDB `releases`. Building with the RocksDB HEAD couple days ago 
 failed because they modified CMake facilities. The latest release (5.17.2) however worked OK.
The next release of Sortmerna will be ready in couple days.

**Comment by adityabandla** [comment]
Have the specs been bundled with v3.0.3, I can't find rocksdb in the 3rdparty folder

**Comment by biocodz** [comment]
RocksDB and ZLib are baked inside the sortmerna binaries. So the binaries are self-contained and should work even if RocksDB and ZLib are not found on the system at all.
I'm going to publish the Centos release today. So, hold on.

**Comment by adityabandla** [comment]
Ok, thanks!
