### ISSUE TITLE
Segmentation fault (core dumped - incorrect use of  '--threads')

### ISSUE THREAD

**Issue by dangchenyuan** [biocore/sortmerna#199]
I just used 2.2K fastq file to remove rRNA, and this error was found.

**Comment by ekopylova** [comment]
Hello,

Could you provide the version number of the software and the exact command with error output? Thanks!

Jenya

**Comment by dangchenyuan** [comment]
@ekopylova thanks a lot. 
my version is 3.0.4
my command is: sortmerna --ref /home/dangchenyuan/softwares/sortmerna-3.0.4/rRNA_databases/silva-bac-16s-id90.fasta,/home/dangchenyuan/softwares/sortmerna-3.0.4/index/silva-bac-16s-id90.idx --reads test.fq --sam --fastx --aligned merge_rRNA  --other merge_no_rRNA  --threads 40
pls see this screenshot

![1572444054(1)](https://user-images.githubusercontent.com/45260772/67864876-50f2ce00-fb61-11e9-9711-0c029939e889.jpg)

**Comment by ekopylova** [comment]
Is it possible for you to share your reads with us, or minimal file that reproduces the error? If we can reproduce it, then much faster to find where it crashes. If that's fine with you, please send me an email at jenya.kopylov at gmail dot com and I'll give you access to a folder where you can upload the data, otherwise a Google drive link ..
Thanks!!

⁣

**Comment by biocodz** [comment]
Please, use `-a 40` instead.  The `--threads 40` (developer option) is not correctly specified (has to be  `--threads 1:1:40`)
This is the same as [Issue 198](https://github.com/biocore/sortmerna/issues/198)
`--threads` option validation is added in Release 4.0 (due in coming days)

**Comment by biocodz** [comment]
We added the necessary validation of the `threads` option in the [release 4.0](https://github.com/biocore/sortmerna/releases/tag/v4.0.0)
