### ISSUE TITLE
merge-paired-reads.sh and unmerged-paired-reads.sh missing from /scripts/

### ISSUE THREAD

**Issue by damselflywingz** [biocore/sortmerna#209]
Hello,

I am looking forward to filtering rRNA from my paired-end data. I followed the instructions to install conda, but when I look in the /scripts/ directory I cannot see the merge-paired-read.sh nor unmerged-paired-read.sh scripts. 

Is there a better way to install the software to ensure the scripts are included in the /scripts/ directory? 

I found a copy of merge-paired-read.sh but I cannot find a copy of unmerged-paired-read.sh anywhere on the internet.
Thanks,
Amber

**Comment by biocodz** [comment]
@damselflywingz The named scripts were removed in version 4.0 because the latest Sortmerna can process 2 files with paired reads without the need for merging. Any previous release before 4.0 should have those scripts e.g. [3.0.4](https://github.com/biocore/sortmerna/archive/v3.0.4.tar.gz)

**Comment by damselflywingz** [comment]
Okay thanks biocodz. I have successfully implemented 4.0.0 in paired-end mode. I used the --fastx and --other options, but my fastq output is interleaved, which needed to be unmerged for the next step of my pipeline. As a follow-up question, is their an option available for sortmerna that outputs aligned (i.e. rRNA) and not-aligned (i.e., non-rRNA) paired-end fastq files?

Thanks,
Amber

**Comment by biocodz** [comment]
If you use `-other` options, the non-aligned reads will be put into a separate file. 
If the reads are paired, both aligned and non-aligned output files will contain paired reads that will need to be separated using the shell script.
The upcoming version 4.0.1 will have an option to write paired reads into separate files.

**Comment by biocodz** [comment]
Since version `4.1.0` the option `-out2` allows to output the filtered paired reads into separate files.

**Comment by terancewong** [comment]
Hi there,
I have a similar issue, but after I typed out -2, and i looked into the details of the automatically produced fwd and rev files, they are not paired. In other words, both forward and reverse files contain /2 reads only (instead of forward reads being /1, and reverse reads being /2). May I know how I could solve this issue? I want mRNA instead of rRNA, so my command is seen as below. 
"sortmerna -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/rfam-5.8s-database-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/rfam-5s-database-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-arc-16s-id95.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-arc-23s-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-bac-16s-id90.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-bac-23s-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-euk-18s-id95.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-euk-28s-id98.fasta \ -reads /home/xuelei/20200109_novogene/stenopus_2/cutadapt/unclassified/pairfq/B_NC_forward.fq -reads /home/xuelei/20200109_novogene/stenopus_2/cutadapt/unclassified/pairfq/B_NC_reverse.fq --aligned B_NC_rRNA --other B_NC_clean  -v --paired_in --fastx -out2

I am looking forward to your advice, thanks!

Yours Sincerely,
Terry

**Comment by biocodz** [comment]
Please, have a look at the [issue 247](https://github.com/biocore/sortmerna/issues/247). It details the current functionality of the `out2` option, and suggests an enhancement.
