### ISSUE TITLE
Increase sensitivity in sorting bacteria/eukaryotic/archaea metatranscriptome rRNA 

### ISSUE THREAD

**Issue by QianqianJena** [biocore/sortmerna#260]
Dear SortmeRNA group,
I am using sortmerna version 2.1 and I run sortmerna to sort mRNA and rRNA from paired metatranscriptome sequences.
Then further sort bacterial 16S/23S rRNA, eukaryotic 18S/28S rRNA, archaea 16S/23S rRNA sequences from the output rRNA file.
Here is the command I run:
1. bacterial 16S rRNA sequences
./sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db --reads IS1_2017_pear_qc_rRNA  --fastx -v -a 20 --aligned IS1_2017_pear_qc_16SrRNA_only --other IS1_2017_pear_qc_no_16SrRNA
2. bacterial 23S rRNA sequences
 ./sortmerna --ref ./rRNA_databases/silva-bac-23s-id98.fasta,./index/silva-bac-23s-db --reads IS1_2017_pear_qc_no_16SrRNA.fastq  --fastx -v -a 20 --aligned IS1_2017_pear_qc_23SrRNA_only --other IS1_2017_pear_qc_no_16S_23S_rRNA
3. eukaryotic 18S rRNA
./sortmerna --ref ./rRNA_databases/silva-euk-18s-id95.fasta,./index/silva-euk-18s-db --reads IS1_2017_pear_qc_no_16S_23S_rRNA.fastq  --fastx -v -a 20 --aligned IS1_2017_pear_qc_18SrRNA_only --other IS1_2017_pear_qc_no_16S_23S_18S_rRNA
4. eukaryotic 28S rRNA
./sortmerna --ref ./rRNA_databases/silva-euk-28s-id98.fasta,./index/silva-euk-28s-db --reads IS1_2017_pear_qc_no_16S_23S_18S_rRNA.fastq  --fastx -v -a 20 --aligned IS1_2017_pear_qc_28SrRNA_only --other IS1_2017_pear_qc_no_16S_23S_18S_28S_rRNA
I found a problem:
If I run the order (1,2,3,4) differently, the number of sequences assigned to each rRNA categories will be different. 

I would like to know if I did something wrong or there is some parameters I can use to improve the sensitivity. I checked the paper that applied sortmerna 2.1 to sort different rRNA sequences. It worked fine for them.

Thanks for your help in advance.
Best regards,
Qian

**Comment by tempsblue** [comment]
Hello @QianqianJena ,

Some short reads (100-250nt) are expected to align with high accuracy to multiple rRNA sequences, either within the same domain and subunit (e.g. multiple high-quality alignments to different 16S bacteria rRNA) or within different close domains and same subunit (e.g. multiple high-quality alignments for the same read in 16S bacteria and 16S archaea) because of high genomic similarity. Therefore, re-ordering your databases can provide different read matches since SortMeRNA will, by default, stop searching for better alignments after the first good match. SortMeRNA was primarily developed to rapidly identify rRNA sequences, rather than high-resolution taxonomy annotation. If you are searching for the latter, you can try running SortMeRNA using the full SILVA database (millions of rRNA sequences) using a very low E-value (e.g. 0.01).

Hope this helps,
Jenya

**Comment by ekopylova** [comment]
Hi @QianqianJena,

To add to the above reply, you can also increase sensitivity with the default databases provided by lowering the E-value threshold (0.01 or 0.001). This should increase number of unique read mappings, though probably will not fully eliminate multiple-mappings.

Jenya

**Comment by QianqianJena** [comment]
Dear Jenya
Thanks Jenya for your reply. Your suggestions are very helpful. 
1. How can convert full silva database to the database that sortmerna can recognize. It would be useful if there is manual available.
2. If I manage these files and set e-value 0.01, how long will sortmerna take to sort 40-90 million sequences?

3. If I stick to the original database and set e-value 0.001, would the sorted sequences be accurate for publishing a paper? Is it right for me to run the above commands, just including one more -e 0.001?

I feel sorry to have so many questions and I really appreciate your kind help.
Thank you a lot.
Best regards,
Qianqian

**Comment by ppericard** [comment]
Hi @QianqianJena ,

If you're trying to sort/classify your reads into those 4 categories, you definitely should concatenate all those reference databases into one single database and then run SortMeRNA mapping, outputting either SAM or BLAST format. By analyzing those alignment files you can then sort and filter alignments in order to identify reads that would match only on one type of rRNA, or reads that would match equally well (based on some score threshold) on several types of rRNAs.

Pierre

**Comment by QianqianJena** [comment]
Dear Pierre,
Thanks for your reply and I think this workflow is good to go.
I will try this method.
Thanks a lot.
Best,
Qianqian
