### ISSUE TITLE
Question on resuming runs

### ISSUE THREAD

**Issue by josruirod** [biocore/sortmerna#268]
Hi, I'm using sortmerna on a daily basis. Thanks for the developing.
I just wanted to ask if there's any way to resume cancelled runs. I'm dealing with huge files and sometimes the runs die because of walltime limits, and it's a problem that we have to rerun from the beginning the samples, even if already spent a lot of hours working.

Is there any way of resuming the latest run? If we don't remove the output folders and the rerun, the process will be resumed?

Thanks for the support

**Comment by biocodz** [comment]
This is a planned feature. Refer to [issue 77](https://github.com/biocore/sortmerna/issues/77)
The request is quite dated, however the good news is by now sortmerna has all the necessary machinery in place to support the restarts because it utilizes a database as the backend storage for the calculations.
Currently our priorities are improving the parallel processing to better utilize HPC capabilities, and fixing a few smaller bugs. This is about 80% done. After that we'll move to enhancements.
So, cheer up and thanks for using Sortmerna.

**Comment by josruirod** [comment]
Great, glad to hear that. Thanks
