### ISSUE TITLE
The ranges of query coverage and subject coverage

### ISSUE THREAD

**Issue by Duannai** [biocore/sortmerna#306]
Hello, I have been working on my metatranscriptomics data.

SortMeRNA is a local alignment tool, thus the query coverage and subject coverage are inportant, especially when the sequences in database are much longer than my reads (150 nt).

What ranges of query coverage and subject coverage do you think are appropriate?

Thanks in advance!

Mort

**Comment by ekopylova** [comment]
Hello @Duannai ,

SortMeRNA uses the e-value to predict rRNA sequences. Though we provide options ```--coverage DBL --id DBL```, these will only be activated together with ```--otu_map ``` in order to output an OTU map compatible with QIIME. The FASTA file will still be computed using the e-value for the threshold, which provides a 99.89% accuracy for selecting rRNA sequences using the default database or, 99.97% using SILVA 119 SSURef & 99.96% for SILVA 138 SSURef NR99. You can add another parameter to output the BLAST tabular file, which will include columns for ID and coverage for each sequence and you can use that to further remove sequences based on your needs.
Best,
Jenya
