### ISSUE TITLE
Still get rRNAs when using the output 'filter.fq' as input to sortmerna the second time

### ISSUE THREAD

**Issue by cf-Rachel** [biocore/sortmerna#333]
Hi,

My question is: since we used sortmerna once, the rRNAs should be revmoved. However, when we used sortmerna for the second time, we still can identify rRNAs. Is there anything wrong in my code?

We performed our analyses using the following pipeline:

1) merge the PE data by  the script "merge-paired-reads.sh"  as follows:
     bash /sortmerna-2.1b/scripts/merge-paired-reads.sh clean_read.r1.fastq clean_read.r2.fastq final_clean_merged_input.fastq
2) perform the sortmerna (use NCBI rRNA  dataset as reference) as follows:
   sortmerna_dir=/sortmerna-2.1b
   sortmerna_script=/sortmerna-4.3.4/sortmerna-4.3.4-Linux/bin
    input=final_clean_merged_input.fastq
    output_dir=/result/test
    time ${sortmerna_script}/sortmerna --threads 20 \
     --ref /ref/ncbi_rRNA0624.fasta \
     --reads $input \
     --workdir $output_dir \
      --fastx --out2 --aligned "$output_dir/test.align" --other "$output_dir/test.filter" -v  --paired_in
3) use the output 'test.filter_fwd.fq' and 'test.filter_rev.fq' as input for STAR (also use NCBI dataset as reference ), and got the results that there still exists multiple rRNAs.
4) use the output 'test.filter_fwd.fq' and 'test.filter_rev.fq' as inputs of sortmerna (first merge them as the same way used in 1)),then we get the new output files of sortmerna: test-filter.align.fwd.fq and test-filter.align.rev.fq 
5) use 'test-filter.align.fwd.fq' and 'test-filter.align.rev.fq' as input of STAR, and the results indicate most of the identified sequences are rRNAs, and the numbers of reads are big.

Thanks!
Best,
Rachel

**Comment by biocodz** [comment]
Hmm, I'll try to create a similar test.
Please, note that it's not necessary to do the merge. Sortmerna can take two reads files as input i.e.
```
sortmerna -ref /ref/ncbi_rRNA0624.fasta -reads clean_read.r1.fastq -reads clean_read.r2.fastq ...
```
Could you provide the location (url) of the `NCBI rRNA dataset`?
Thank you for filing this problem.

**Comment by cf-Rachel** [comment]
Hi, thanks for the nice suggestion. We added -e 10000 and solve the problem. 
However, I still have some quesions:
1) when we used the '-reads clean_r1.fastq -reads clean_r2.fastq', should we get four results such as 'r1_fwd.fq, r1_rev.fq, r2_fwd.fq, r2_rev.fq'? How should we set this? We tried but failed.  
2) we could use 1000G memory, and the size of input reads may be 30GB. How should we set -m to get the results faster?
3) in the 'align.log', when we use '--paired_in', the number given by "Total reads failing E-value threshold" was bigger than the actual reads number in the 'filter.fq'. Is it the reason illustrated in the manual that 'However, there are small chances that reads which are non-rRNA will also be put into the --aligned file.'
4) In the 'align.log', I got the following result:
    Minimum read length = 100
    Maximum read length = 19
   should it be 
    Maxmum read length = 100
    Minimum read length = 19

Thanks very much! And thank you for developing Sortmerna, it helps us a lot!

best,
Rachel

**Comment by Amaval25** [comment]
I am trying to clean the rRNA sequences from my transcriptomes in order to make a reference transcriptome de novo. I ran my script several times with modifications, but I can’t generate any information inside the out folder. 
I understand that I must expect at least one of these 6 files: aligned.log, aligned.blast, aligned_fwd.fq, aligned_rev.fq, other_fwd.fq, other_rev.fq.  However, my out folder is empty. On the other hand, I get several files fwd.fq and rev.fq and I don’t understand if those are really the filtered sequences.
SortMeRNA version 4.3.6
#Definir ruta de directorio de salida
OUTPUT_DIR="/mnt/d/TERMITAS_Analysis_Macrogen_2024/non_rRNA_reads_2"
sortmerna --threads 20 -ref /mnt/d/TERMITAS_Analysis_Macrogen_2024/sortmerna_db/DBase/silva-bac-16s-id90.fasta -ref /mnt/d/TERMITAS_Analysis_Macrogen_2024/sortmerna_db/DBase/silva-euk-18s-id95.fasta -ref /mnt/d/TERMITAS_Analysis_Macrogen_2024/sortmerna_db/DBase/silva-bac-23s-id98.fasta -ref /mnt/d/TERMITAS_Analysis_Macrogen_2024/sortmerna_db/DBase/silva-euk-28s-id98.fasta -ref /mnt/d/TERMITAS_Analysis_Macrogen_2024/sortmerna_db/DBase/rfam-5.8s-database-id98.fasta -reads /mnt/d/TERMITAS_Analysis_Macrogen_2024/filtered_reads/Alates_2_1_filtered.fastq -reads /mnt/d/TERMITAS_Analysis_Macrogen_2024/filtered_reads/Alates_2_2_filtered.fastq -workdir "${OUTPUT_DIR}/Alates_2_workdir" -fastx -paired_in -blast 1 -num_alignments 1 -sam


[processin_Alates.txt](https://github.com/user-attachments/files/18693158/processin_Alates.txt)

**Comment by biocodz** [comment]
The process was interrupted `./filtered_sortmerna_2.sh: line 5:   642 Killed` for some reason, so the output was not generated.
Your machine has only 8 cores, so using 20 threads doesn't make sense. Probably just use 6 i.e. `-threads 6`

**Comment by Amaval25** [comment]
Thank you very much, it’s the first time I’m analyzing this type of data.
As you can see, I am not a bioinformatician. I hope that with this change
can generate output.
Again, thank you so much for taking the time to answer.
