### ISSUE TITLE
harcoded path in test_sortmerna.py

### ISSUE THREAD

**Issue by adamrp** [biocore/sortmerna#55]
[this line](https://github.com/biocore/sortmerna/blob/master/tests/test_sortmerna.py#L34) is causing tests to fail on my system, and the only way to fix it is to change the code on my local installation.

**Comment by ekopylova** [comment]
These tests were written mostly for me to run prior to pushing any PRs into the master branch. I'm not sure if it's possible to pass arguments to unit tests, since they should be self contained. As I'm testing the functionality of the program here rather than individual methods, the input files are relatively large in size and needed to be stored in an external directory. That line should be edited to the filepath where the input files are stored. I haven't pushed this collection into the master thread but will probably create another branch for it. Were you planning on running these tests for QIIME setup installation or something else? I agree this area needs some work, but have been tied up with other more urgent projects.

**Comment by ekopylova** [comment]
That line has been changed to:
```self.root = join(dirname(abspath(__file__)), "data")```
and now does not require editing the code.
