### ISSUE TITLE
"threads" and "memory" arguments apparently ignored

### ISSUE THREAD

**Issue by jvollme** [biocore/sortmerna#69]
Hi, I am currently using SortMeRNA version 2.0 on a linux system running Ubuntu 14.04 with 32 cores and 80 GB RAM. 
I started sortmerna on a large set of illumina reads, using the **"-a"** and **"-m"** arguments to specify 16 parallel threads and 32 Gb RAM-usage  **("-a 16 -m 32000")**. However, sortmeRNA is using only *one* single core and is currently taking much, much longer to run than I remember from previous versions.
The memory consumption is a bit unclear as "gnome-system-monitor" tells me it is using less than a megabyte (unrealistic), while "htop" tells me it is using more than 17Gb RAM (also unrealistic because the "free" command shows that max 6 Gb RAM are currently in use.

Here is my complete command: 
``sortmerna -v -a 16 -m 32000 --reads myreads.fastq --ref /usr/local/tools/sortmerna-2.0/./rRNA_databases/silva-bac-16s-id90.fasta,/usr/local/tools/sortmerna-2.0/./index/silva-bac-16s-db:/usr/local/tools/sortmerna-2.0/./rRNA_databases/silva-arc-16s-id95.fasta,/usr/local/tools/sortmerna-2.0/./index/silva-arc-16s-db:/usr/local/tools/sortmerna-2.0/./rRNA_databases/silva-euk-18s-id95.fasta,/usr/local/tools/sortmerna-2.0/./index/silva-euk-18s-db --aligned ./SSU_rRNA_reads_myreads --log --fastx --blast 3 --pid``

did I do something wrong?

**Comment by ekopylova** [comment]
Hello,

I've created an issue on the "-m" argument [here](https://github.com/biocore/sortmerna/issues/70). For some reason setting larger '-m' values halts the program at the memory mapping step. The threads option '-a' is used only after all the reads are loaded into memory, as this step is not being carried out, you're only seeing 1 thread active.

I'll spend sometime in the next few weeks to figure out what the issue is, but until then if you use the default '-m' option (which mmap's 1GB of reads at a time) then you should have no issues with setting '-a' to the maximum number of threads available on your system given your RAM capacity.

Otherwise your command looks correct.

Thanks for reporting this!
Jenya

**Comment by jvollme** [comment]
after leaving out the "-m" argument, the script now works (with the speed that I'm used to), thanks!
