### ISSUE TITLE
more efficient cleaning

### ISSUE THREAD

**Issue by sghignone** [biocore/sortmerna#73]
Dear developer,
actually this is not an issue report.
We filtered our tomato root metatranscriptome dataset using SortMeRNA with built-in silva and rfam reference databases plus the UNITE_7 release (fungal ITS), RDP (only Archaea and Fungi) and a custom tomato rRNA obtained through NCBI.
`sortmerna --ref [all the indexed references] --fastx --blast 1 --log -a 2 -v `
However, a MG-RAST server analyis of survived reads showed about 2159 persisiting rRNA sequences (0.4% of total sequences and matching mostly on SILVA and RDP databases).
Is there a better method (in term commad line parameters) to even more efficently clean our dataset? should we include any other additional reference dataset ?
An extra question: is SortMeRNA optimized for clustered references databases or we can index and perform analysis on complete SILVA databases?

thanks

stefano

**Comment by ekopylova** [comment]
Hi Stefano,

Since the distributed rRNA databases are clustered references, as you note, they contain a small fraction of total rRNA found in complete SILVA. Perhaps the 0.4% rRNA are more distant sequences and failed to align to the representative databases with the default E-value threshold 1. Some parameters that increase sensitivity with the same databases are: (a) a lower seed length (`-L 16`) when indexing the databases (b) more locations on the read where a seed is searched (`--passes 18,9,1` for default seed length or `--passes 16,8,1` if you use seed length = 16) (b) higher E-value (ex. `-e 10`).

Indeed you can work with the complete SILVA databases. Although, depending on how large your metatranscriptome is, this may take a lot longer to compute.

If you provide me with a few of the 2159 rRNA sequences that passed the filter (matching to SILVA), I can quickly check which parameter setting would be better.

Jenya
